// <auto-generated />
using MVC_1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("MVC_1.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Історія родини мафіозі Корлеоне та боротьби за владу в кримінальному світі Нью-Йорка.",
                            Director = "Френсіс Форд Коппола",
                            Genre = "Драма, кримінал",
                            PosterUrl = "https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg",
                            Title = "Хрещений батько",
                            Year = 1972
                        },
                        new
                        {
                            Id = 2,
                            Description = "Банкір, засуджений за вбивство, яке не скоював, шукає надію та свободу у в'язниці Шоушенк.",
                            Director = "Френк Дарабонт",
                            Genre = "Драма",
                            PosterUrl = "https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg",
                            Title = "Втеча з Шоушенку",
                            Year = 1994
                        },
                        new
                        {
                            Id = 3,
                            Description = "Бетмен протистоїть Джокеру, який занурює Готем у хаос та анархію.",
                            Director = "Крістофер Нолан",
                            Genre = "Бойовик, драма",
                            PosterUrl = "https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg",
                            Title = "Темний лицар",
                            Year = 2008
                        },
                        new
                        {
                            Id = 4,
                            Description = "Команда дослідників подорожує крізь червоточину у пошуках нового дому для людства.",
                            Director = "Крістофер Нолан",
                            Genre = "Фантастика, драма",
                            PosterUrl = "https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg",
                            Title = "Інтерстеллар",
                            Year = 2014
                        },
                        new
                        {
                            Id = 5,
                            Description = "Історія життя простодушного чоловіка, який став свідком і учасником ключових подій американської історії.",
                            Director = "Роберт Земекіс",
                            Genre = "Драма, комедія",
                            PosterUrl = "https://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg",
                            Title = "Форрест Гамп",
                            Year = 1994
                        },
                        new
                        {
                            Id = 6,
                            Description = "Переплетені історії двох найманих вбивць, боксера та дружини гангстера в Лос-Анджелесі.",
                            Director = "Квентін Тарантіно",
                            Genre = "Кримінал, драма",
                            PosterUrl = "https://upload.wikimedia.org/wikipedia/en/3/3b/Pulp_Fiction_%281994%29_poster.jpg",
                            Title = "Кримінальне чтиво",
                            Year = 1994
                        },
                        new
                        {
                            Id = 7,
                            Description = "Злодій, який краде секрети зі снів, отримує завдання навпаки — впровадити ідею в чужу підсвідомість.",
                            Director = "Крістофер Нолан",
                            Genre = "Фантастика, трилер",
                            PosterUrl = "https://avatars.mds.yandex.net/get-kinopoisk-image/1629390/8ab9a119-dd74-44f0-baec-0629797483d7/600x900",
                            Title = "Початок",
                            Year = 2010
                        },
                        new
                        {
                            Id = 8,
                            Description = "Програміст дізнається, що реальність навколо нього — симуляція, і приєднується до повстання проти машин.",
                            Director = "Лана та Ліллі Вачовскі",
                            Genre = "Фантастика, бойовик",
                            PosterUrl = "https://thumb.wikimedia.org/wikipedia/ru/thumb/9/9d/Matrix-DVD.jpg/250px-Matrix-DVD.jpg?utm_source=ru.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
                            Title = "Матриця",
                            Year = 1999
                        },
                        new
                        {
                            Id = 9,
                            Description = "Офісний працівник, страждаючи від безсоння, засновує підпільний бійцівський клуб зі своїм новим знайомим.",
                            Director = "Девід Фінчер",
                            Genre = "Драма",
                            PosterUrl = "https://upload.wikimedia.org/wikipedia/en/f/fc/Fight_Club_poster.jpg",
                            Title = "Бійцівський клуб",
                            Year = 1999
                        },
                        new
                        {
                            Id = 10,
                            Description = "Гобіт Фродо вирушає у небезпечну подорож, щоб знищити могутній перстень і врятувати Середзем'я.",
                            Director = "Пітер Джексон",
                            Genre = "Фентезі, пригоди",
                            PosterUrl = "https://thumb.wikimedia.org/wikipedia/uk/thumb/8/8c/%D0%91%D1%80%D0%B0%D1%82%D1%81%D1%82%D0%B2%D0%BE_%D0%9F%D0%B5%D1%80%D1%81%D0%BD%D1%8F.jpg/250px-%D0%91%D1%80%D0%B0%D1%82%D1%81%D1%82%D0%B2%D0%BE_%D0%9F%D0%B5%D1%80%D1%81%D0%BD%D1%8F.jpg?utm_source=uk.wikipedia.org&utm_campaign=parser&utm_content=thumbnail",
                            Title = "Володар перснів: Братство персня",
                            Year = 2001
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
